kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logging-configmap-reader
  namespace: openshift-logging
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - sharing-config
  verbs:
  - get
