kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-operator
  namespace: openshift-logging
roleRef:
  kind: Role
  name: logging-configmap-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: console-operator
    namespace: openshift-console-operator